export const genres = [
  'acoustic',
  'afrobeat',
  'alt-rock',
  'alternative',
  'ambient',
  'anime',
  'black-metal',
  'bluegrass',
  'blues',
  'bossanova',
  'brazil',
  'breakbeat',
  'british',
  'cantopop',
  'chicago-house',
  'children',
  'chill',
  'classical',
  'club',
  'comedy',
  'country',
  'dance',
  'dancehall',
  'death-metal',
  'deep-house',
  'detroit-techno',
  'disco',
  'disney',
  'drum-and-bass',
  'dub',
  'dubstep',
  'edm',
  'electro',
  'electronic',
  'emo',
  'folk',
  'forro',
  'french',
  'funk',
  'garage',
  'german',
  'gospel',
  'goth',
  'grindcore',
  'groove',
  'grunge',
  'guitar',
  'happy',
  'hard-rock',
  'hardcore',
  'hardstyle',
  'heavy-metal',
  'hip-hop',
  'holidays',
  'honky-tonk',
  'house',
  'idm',
  'indian',
  'indie',
  'indie-pop',
  'industrial',
  'iranian',
  'j-dance',
  'j-idol',
  'j-pop',
  'j-rock',
  'jazz',
  'k-pop',
  'kids',
  'latin',
  'latino',
  'malay',
  'mandopop',
  'metal',
  'metal-misc',
  'metalcore',
  'minimal-techno',
  'movies',
  'mpb',
  'new-age',
  'new-release',
  'opera',
  'pagode',
  'party',
  'philippines-opm',
  'piano',
  'pop',
  'pop-film',
  'post-dubstep',
  'power-pop',
  'progressive-house',
  'psych-rock',
  'punk',
  'punk-rock',
  'r-n-b',
  'rainy-day',
  'reggae',
  'reggaeton',
  'road-trip',
  'rock',
  'rock-n-roll',
  'rockabilly',
  'romance',
  'sad',
  'salsa',
  'samba',
  'sertanejo',
  'show-tunes',
  'singer-songwriter',
  'ska',
  'sleep',
  'songwriter',
  'soul',
  'soundtracks',
  'spanish',
  'study',
  'summer',
  'swedish',
  'synth-pop',
  'tango',
  'techno',
  'trance',
  'trip-hop',
  'turkish',
  'work-out',
  'world-music',
];

export const tracks = [
  {
    album: {
      album_type: 'ALBUM',
      total_tracks: 14,
      external_urls: {
        spotify: 'https://open.spotify.com/album/3mb6QMOelljOicaqCo4F6i',
      },
      href: 'https://api.spotify.com/v1/albums/3mb6QMOelljOicaqCo4F6i',
      id: '3mb6QMOelljOicaqCo4F6i',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b273a87bf0009599d8100f78e464',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e02a87bf0009599d8100f78e464',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00004851a87bf0009599d8100f78e464',
          height: 64,
          width: 64,
        },
      ],
      name: 'That Lonesome Song',
      release_date: '2008-01-01',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:3mb6QMOelljOicaqCo4F6i',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/5yhxqYI0JBwUKfXpSEjiM8',
          },
          href: 'https://api.spotify.com/v1/artists/5yhxqYI0JBwUKfXpSEjiM8',
          id: '5yhxqYI0JBwUKfXpSEjiM8',
          name: 'Jamey Johnson',
          type: 'artist',
          uri: 'spotify:artist:5yhxqYI0JBwUKfXpSEjiM8',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/5yhxqYI0JBwUKfXpSEjiM8',
        },
        href: 'https://api.spotify.com/v1/artists/5yhxqYI0JBwUKfXpSEjiM8',
        id: '5yhxqYI0JBwUKfXpSEjiM8',
        name: 'Jamey Johnson',
        type: 'artist',
        uri: 'spotify:artist:5yhxqYI0JBwUKfXpSEjiM8',
      },
    ],
    disc_number: 1,
    duration_ms: 345120,
    explicit: false,
    external_ids: {
      isrc: 'USUM70820162',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/73sWpECi7iZrcISLSRxuaH',
    },
    href: 'https://api.spotify.com/v1/tracks/73sWpECi7iZrcISLSRxuaH',
    id: '73sWpECi7iZrcISLSRxuaH',
    is_playable: true,
    name: 'High Cost Of Living',
    popularity: 61,
    preview_url: null,
    track_number: 2,
    type: 'track',
    uri: 'spotify:track:73sWpECi7iZrcISLSRxuaH',
    is_local: false,
  },
  {
    album: {
      album_type: 'ALBUM',
      total_tracks: 13,
      external_urls: {
        spotify: 'https://open.spotify.com/album/23cuZhPWDfX1uKD4qwuv7t',
      },
      href: 'https://api.spotify.com/v1/albums/23cuZhPWDfX1uKD4qwuv7t',
      id: '23cuZhPWDfX1uKD4qwuv7t',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b2734686b4078ad5eb92315d28e0',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e024686b4078ad5eb92315d28e0',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d000048514686b4078ad5eb92315d28e0',
          height: 64,
          width: 64,
        },
      ],
      name: 'Current Mood',
      release_date: '2017-09-08',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:23cuZhPWDfX1uKD4qwuv7t',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/1dID9zgn0OV0Y8ud7Mh2tS',
          },
          href: 'https://api.spotify.com/v1/artists/1dID9zgn0OV0Y8ud7Mh2tS',
          id: '1dID9zgn0OV0Y8ud7Mh2tS',
          name: 'Dustin Lynch',
          type: 'artist',
          uri: 'spotify:artist:1dID9zgn0OV0Y8ud7Mh2tS',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/1dID9zgn0OV0Y8ud7Mh2tS',
        },
        href: 'https://api.spotify.com/v1/artists/1dID9zgn0OV0Y8ud7Mh2tS',
        id: '1dID9zgn0OV0Y8ud7Mh2tS',
        name: 'Dustin Lynch',
        type: 'artist',
        uri: 'spotify:artist:1dID9zgn0OV0Y8ud7Mh2tS',
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/3RXtieA0L2l22SWlOUMNca',
        },
        href: 'https://api.spotify.com/v1/artists/3RXtieA0L2l22SWlOUMNca',
        id: '3RXtieA0L2l22SWlOUMNca',
        name: 'Karen Fairchild',
        type: 'artist',
        uri: 'spotify:artist:3RXtieA0L2l22SWlOUMNca',
      },
    ],
    disc_number: 1,
    duration_ms: 245080,
    explicit: false,
    external_ids: {
      isrc: 'QMRSZ1701898',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/06n8e1GbmK3b7ZHv20N8Jl',
    },
    href: 'https://api.spotify.com/v1/tracks/06n8e1GbmK3b7ZHv20N8Jl',
    id: '06n8e1GbmK3b7ZHv20N8Jl',
    is_playable: true,
    name: 'Love Me Or Leave Me Alone (feat. Karen Fairchild)',
    popularity: 46,
    preview_url:
      'https://p.scdn.co/mp3-preview/0d7555e73019eacb99870ce0ce0f21af741bed8c?cid=860f7e542d28458ba23dd153a3319256',
    track_number: 6,
    type: 'track',
    uri: 'spotify:track:06n8e1GbmK3b7ZHv20N8Jl',
    is_local: false,
  },
  {
    album: {
      album_type: 'ALBUM',
      total_tracks: 11,
      external_urls: {
        spotify: 'https://open.spotify.com/album/3qFNiOv7yX8pueke4P6Z8c',
      },
      href: 'https://api.spotify.com/v1/albums/3qFNiOv7yX8pueke4P6Z8c',
      id: '3qFNiOv7yX8pueke4P6Z8c',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b273e4b91408230ed6a68099b1c8',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e02e4b91408230ed6a68099b1c8',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00004851e4b91408230ed6a68099b1c8',
          height: 64,
          width: 64,
        },
      ],
      name: 'Chris Cagle',
      release_date: '2003-01-01',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:3qFNiOv7yX8pueke4P6Z8c',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/1zhIzONVRlTfD1VQRauHMl',
          },
          href: 'https://api.spotify.com/v1/artists/1zhIzONVRlTfD1VQRauHMl',
          id: '1zhIzONVRlTfD1VQRauHMl',
          name: 'Chris Cagle',
          type: 'artist',
          uri: 'spotify:artist:1zhIzONVRlTfD1VQRauHMl',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/1zhIzONVRlTfD1VQRauHMl',
        },
        href: 'https://api.spotify.com/v1/artists/1zhIzONVRlTfD1VQRauHMl',
        id: '1zhIzONVRlTfD1VQRauHMl',
        name: 'Chris Cagle',
        type: 'artist',
        uri: 'spotify:artist:1zhIzONVRlTfD1VQRauHMl',
      },
    ],
    disc_number: 1,
    duration_ms: 210560,
    explicit: false,
    external_ids: {
      isrc: 'USCN10300094',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/0nprj2O0teCglthuhzTG5o',
    },
    href: 'https://api.spotify.com/v1/tracks/0nprj2O0teCglthuhzTG5o',
    id: '0nprj2O0teCglthuhzTG5o',
    is_playable: true,
    name: 'Chicks Dig It - Single Edit',
    popularity: 60,
    preview_url: null,
    track_number: 2,
    type: 'track',
    uri: 'spotify:track:0nprj2O0teCglthuhzTG5o',
    is_local: false,
  },
  {
    album: {
      album_type: 'SINGLE',
      total_tracks: 1,
      external_urls: {
        spotify: 'https://open.spotify.com/album/6TuDxNLQS8xIuHAJL91EDi',
      },
      href: 'https://api.spotify.com/v1/albums/6TuDxNLQS8xIuHAJL91EDi',
      id: '6TuDxNLQS8xIuHAJL91EDi',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b273e937bfe6531c73d5b1892328',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e02e937bfe6531c73d5b1892328',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00004851e937bfe6531c73d5b1892328',
          height: 64,
          width: 64,
        },
      ],
      name: 'Right Girl Wrong Time',
      release_date: '2017-04-28',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:6TuDxNLQS8xIuHAJL91EDi',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/4BANbHDs1IluagTx5eRW2P',
          },
          href: 'https://api.spotify.com/v1/artists/4BANbHDs1IluagTx5eRW2P',
          id: '4BANbHDs1IluagTx5eRW2P',
          name: 'Jon Langston',
          type: 'artist',
          uri: 'spotify:artist:4BANbHDs1IluagTx5eRW2P',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/4BANbHDs1IluagTx5eRW2P',
        },
        href: 'https://api.spotify.com/v1/artists/4BANbHDs1IluagTx5eRW2P',
        id: '4BANbHDs1IluagTx5eRW2P',
        name: 'Jon Langston',
        type: 'artist',
        uri: 'spotify:artist:4BANbHDs1IluagTx5eRW2P',
      },
    ],
    disc_number: 1,
    duration_ms: 222893,
    explicit: false,
    external_ids: {
      isrc: 'US7VG1745875',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/3l4ocz4JRx92xTAnqNTgGG',
    },
    href: 'https://api.spotify.com/v1/tracks/3l4ocz4JRx92xTAnqNTgGG',
    id: '3l4ocz4JRx92xTAnqNTgGG',
    is_playable: true,
    name: 'Right Girl Wrong Time',
    popularity: 54,
    preview_url: null,
    track_number: 1,
    type: 'track',
    uri: 'spotify:track:3l4ocz4JRx92xTAnqNTgGG',
    is_local: false,
  },
  {
    album: {
      album_type: 'ALBUM',
      total_tracks: 15,
      external_urls: {
        spotify: 'https://open.spotify.com/album/6gYk1JlSSmlUZGs1Lef1BI',
      },
      href: 'https://api.spotify.com/v1/albums/6gYk1JlSSmlUZGs1Lef1BI',
      id: '6gYk1JlSSmlUZGs1Lef1BI',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b27330fb8097859c939e15124037',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e0230fb8097859c939e15124037',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d0000485130fb8097859c939e15124037',
          height: 64,
          width: 64,
        },
      ],
      name: 'My Kinda Party',
      release_date: '2010-11-02',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:6gYk1JlSSmlUZGs1Lef1BI',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/3FfvYsEGaIb52QPXhg4DcH',
          },
          href: 'https://api.spotify.com/v1/artists/3FfvYsEGaIb52QPXhg4DcH',
          id: '3FfvYsEGaIb52QPXhg4DcH',
          name: 'Jason Aldean',
          type: 'artist',
          uri: 'spotify:artist:3FfvYsEGaIb52QPXhg4DcH',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/3FfvYsEGaIb52QPXhg4DcH',
        },
        href: 'https://api.spotify.com/v1/artists/3FfvYsEGaIb52QPXhg4DcH',
        id: '3FfvYsEGaIb52QPXhg4DcH',
        name: 'Jason Aldean',
        type: 'artist',
        uri: 'spotify:artist:3FfvYsEGaIb52QPXhg4DcH',
      },
    ],
    disc_number: 1,
    duration_ms: 284960,
    explicit: false,
    external_ids: {
      isrc: 'US58E1000227',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/215FCyLSBcXeX0NASXEjyn',
    },
    href: 'https://api.spotify.com/v1/tracks/215FCyLSBcXeX0NASXEjyn',
    id: '215FCyLSBcXeX0NASXEjyn',
    is_playable: true,
    name: 'My Kinda Party',
    popularity: 68,
    preview_url:
      'https://p.scdn.co/mp3-preview/fea1508fcc2c72fde8ec02e33c0793f005aa1590?cid=860f7e542d28458ba23dd153a3319256',
    track_number: 4,
    type: 'track',
    uri: 'spotify:track:215FCyLSBcXeX0NASXEjyn',
    is_local: false,
  },
  {
    album: {
      album_type: 'ALBUM',
      total_tracks: 11,
      external_urls: {
        spotify: 'https://open.spotify.com/album/6ReptrLRzFQ07VxrsN3CZG',
      },
      href: 'https://api.spotify.com/v1/albums/6ReptrLRzFQ07VxrsN3CZG',
      id: '6ReptrLRzFQ07VxrsN3CZG',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b273e5b302f7c3ae39eb191ae3ee',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e02e5b302f7c3ae39eb191ae3ee',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00004851e5b302f7c3ae39eb191ae3ee',
          height: 64,
          width: 64,
        },
      ],
      name: 'Modern Day Drifter',
      release_date: '2005-01-01',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:6ReptrLRzFQ07VxrsN3CZG',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/7x8nK0m0cP2ksQf0mjWdPS',
          },
          href: 'https://api.spotify.com/v1/artists/7x8nK0m0cP2ksQf0mjWdPS',
          id: '7x8nK0m0cP2ksQf0mjWdPS',
          name: 'Dierks Bentley',
          type: 'artist',
          uri: 'spotify:artist:7x8nK0m0cP2ksQf0mjWdPS',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/7x8nK0m0cP2ksQf0mjWdPS',
        },
        href: 'https://api.spotify.com/v1/artists/7x8nK0m0cP2ksQf0mjWdPS',
        id: '7x8nK0m0cP2ksQf0mjWdPS',
        name: 'Dierks Bentley',
        type: 'artist',
        uri: 'spotify:artist:7x8nK0m0cP2ksQf0mjWdPS',
      },
    ],
    disc_number: 1,
    duration_ms: 281973,
    explicit: false,
    external_ids: {
      isrc: 'USCN10500029',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/6yFD0TSZvxydqGxLNDjZUO',
    },
    href: 'https://api.spotify.com/v1/tracks/6yFD0TSZvxydqGxLNDjZUO',
    id: '6yFD0TSZvxydqGxLNDjZUO',
    is_playable: true,
    name: 'Come A Little Closer',
    popularity: 56,
    preview_url: null,
    track_number: 2,
    type: 'track',
    uri: 'spotify:track:6yFD0TSZvxydqGxLNDjZUO',
    is_local: false,
  },
  {
    album: {
      album_type: 'ALBUM',
      total_tracks: 10,
      external_urls: {
        spotify: 'https://open.spotify.com/album/3iu3dv8VOgYZFV9nypUmb3',
      },
      href: 'https://api.spotify.com/v1/albums/3iu3dv8VOgYZFV9nypUmb3',
      id: '3iu3dv8VOgYZFV9nypUmb3',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b273048cb5506c49eab53043f081',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e02048cb5506c49eab53043f081',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00004851048cb5506c49eab53043f081',
          height: 64,
          width: 64,
        },
      ],
      name: 'Super Hits',
      release_date: '1971',
      release_date_precision: 'year',
      type: 'album',
      uri: 'spotify:album:3iu3dv8VOgYZFV9nypUmb3',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/0DchahWJGQqrqr8PMM5zQD',
          },
          href: 'https://api.spotify.com/v1/artists/0DchahWJGQqrqr8PMM5zQD',
          id: '0DchahWJGQqrqr8PMM5zQD',
          name: 'Johnny Paycheck',
          type: 'artist',
          uri: 'spotify:artist:0DchahWJGQqrqr8PMM5zQD',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/0DchahWJGQqrqr8PMM5zQD',
        },
        href: 'https://api.spotify.com/v1/artists/0DchahWJGQqrqr8PMM5zQD',
        id: '0DchahWJGQqrqr8PMM5zQD',
        name: 'Johnny Paycheck',
        type: 'artist',
        uri: 'spotify:artist:0DchahWJGQqrqr8PMM5zQD',
      },
    ],
    disc_number: 1,
    duration_ms: 156293,
    explicit: false,
    external_ids: {
      isrc: 'USSM17700228',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/4XbxeoBeQnwpsyJyZEMoWc',
    },
    href: 'https://api.spotify.com/v1/tracks/4XbxeoBeQnwpsyJyZEMoWc',
    id: '4XbxeoBeQnwpsyJyZEMoWc',
    is_playable: true,
    name: 'Take This Job and Shove It',
    popularity: 60,
    preview_url:
      'https://p.scdn.co/mp3-preview/b7899ba3ffd5804833bb8a27fc56792a64b6fe03?cid=860f7e542d28458ba23dd153a3319256',
    track_number: 10,
    type: 'track',
    uri: 'spotify:track:4XbxeoBeQnwpsyJyZEMoWc',
    is_local: false,
  },
  {
    album: {
      album_type: 'ALBUM',
      total_tracks: 11,
      external_urls: {
        spotify: 'https://open.spotify.com/album/2ewYJg5AuA9bXWrvOs1mtB',
      },
      href: 'https://api.spotify.com/v1/albums/2ewYJg5AuA9bXWrvOs1mtB',
      id: '2ewYJg5AuA9bXWrvOs1mtB',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b2739fd857fb9120e851eb0c68ea',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e029fd857fb9120e851eb0c68ea',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d000048519fd857fb9120e851eb0c68ea',
          height: 64,
          width: 64,
        },
      ],
      name: 'Down The Road I Go',
      release_date: '2000-10-01',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:2ewYJg5AuA9bXWrvOs1mtB',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/2M4Yt7oKGoYd0wqU44k4i2',
          },
          href: 'https://api.spotify.com/v1/artists/2M4Yt7oKGoYd0wqU44k4i2',
          id: '2M4Yt7oKGoYd0wqU44k4i2',
          name: 'Travis Tritt',
          type: 'artist',
          uri: 'spotify:artist:2M4Yt7oKGoYd0wqU44k4i2',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/2M4Yt7oKGoYd0wqU44k4i2',
        },
        href: 'https://api.spotify.com/v1/artists/2M4Yt7oKGoYd0wqU44k4i2',
        id: '2M4Yt7oKGoYd0wqU44k4i2',
        name: 'Travis Tritt',
        type: 'artist',
        uri: 'spotify:artist:2M4Yt7oKGoYd0wqU44k4i2',
      },
    ],
    disc_number: 1,
    duration_ms: 241533,
    explicit: false,
    external_ids: {
      isrc: 'USSM10012734',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/3oW6SWwGqiZSPTiAp7ZQoH',
    },
    href: 'https://api.spotify.com/v1/tracks/3oW6SWwGqiZSPTiAp7ZQoH',
    id: '3oW6SWwGqiZSPTiAp7ZQoH',
    is_playable: true,
    name: "It's A Great Day To Be Alive",
    popularity: 75,
    preview_url:
      'https://p.scdn.co/mp3-preview/9ebae0d96a0264e5e32fbc0b1e787ec72f413824?cid=860f7e542d28458ba23dd153a3319256',
    track_number: 4,
    type: 'track',
    uri: 'spotify:track:3oW6SWwGqiZSPTiAp7ZQoH',
    is_local: false,
  },
  {
    album: {
      album_type: 'SINGLE',
      total_tracks: 1,
      external_urls: {
        spotify: 'https://open.spotify.com/album/1CmyiTVCeiB2FTlxK1afes',
      },
      href: 'https://api.spotify.com/v1/albums/1CmyiTVCeiB2FTlxK1afes',
      id: '1CmyiTVCeiB2FTlxK1afes',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b2731c93430b7707763837b4c7d2',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e021c93430b7707763837b4c7d2',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d000048511c93430b7707763837b4c7d2',
          height: 64,
          width: 64,
        },
      ],
      name: 'What Ever Happened',
      release_date: '2018-02-23',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:1CmyiTVCeiB2FTlxK1afes',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/1nf0nRF0W4ybnJdda00pKY',
          },
          href: 'https://api.spotify.com/v1/artists/1nf0nRF0W4ybnJdda00pKY',
          id: '1nf0nRF0W4ybnJdda00pKY',
          name: 'The Swon Brothers',
          type: 'artist',
          uri: 'spotify:artist:1nf0nRF0W4ybnJdda00pKY',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/1nf0nRF0W4ybnJdda00pKY',
        },
        href: 'https://api.spotify.com/v1/artists/1nf0nRF0W4ybnJdda00pKY',
        id: '1nf0nRF0W4ybnJdda00pKY',
        name: 'The Swon Brothers',
        type: 'artist',
        uri: 'spotify:artist:1nf0nRF0W4ybnJdda00pKY',
      },
    ],
    disc_number: 1,
    duration_ms: 220010,
    explicit: false,
    external_ids: {
      isrc: 'QZ5AB1864880',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/6K2DEAxxbtp7yAsvqYzgOn',
    },
    href: 'https://api.spotify.com/v1/tracks/6K2DEAxxbtp7yAsvqYzgOn',
    id: '6K2DEAxxbtp7yAsvqYzgOn',
    is_playable: true,
    name: 'What Ever Happened',
    popularity: 21,
    preview_url:
      'https://p.scdn.co/mp3-preview/7d7aa7ed6d2ab46255527850471061db27a8fa08?cid=860f7e542d28458ba23dd153a3319256',
    track_number: 1,
    type: 'track',
    uri: 'spotify:track:6K2DEAxxbtp7yAsvqYzgOn',
    is_local: false,
  },
  {
    album: {
      album_type: 'COMPILATION',
      total_tracks: 37,
      external_urls: {
        spotify: 'https://open.spotify.com/album/14Rzkbo8X4bDRqrWXajJyF',
      },
      href: 'https://api.spotify.com/v1/albums/14Rzkbo8X4bDRqrWXajJyF',
      id: '14Rzkbo8X4bDRqrWXajJyF',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b2736be087f5fce49a28fd943317',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e026be087f5fce49a28fd943317',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d000048516be087f5fce49a28fd943317',
          height: 64,
          width: 64,
        },
      ],
      name: 'The Essential Alan Jackson',
      release_date: '2010-11-23',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:14Rzkbo8X4bDRqrWXajJyF',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/4mxWe1mtYIYfP040G38yvS',
          },
          href: 'https://api.spotify.com/v1/artists/4mxWe1mtYIYfP040G38yvS',
          id: '4mxWe1mtYIYfP040G38yvS',
          name: 'Alan Jackson',
          type: 'artist',
          uri: 'spotify:artist:4mxWe1mtYIYfP040G38yvS',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/4mxWe1mtYIYfP040G38yvS',
        },
        href: 'https://api.spotify.com/v1/artists/4mxWe1mtYIYfP040G38yvS',
        id: '4mxWe1mtYIYfP040G38yvS',
        name: 'Alan Jackson',
        type: 'artist',
        uri: 'spotify:artist:4mxWe1mtYIYfP040G38yvS',
      },
    ],
    disc_number: 1,
    duration_ms: 270600,
    explicit: false,
    external_ids: {
      isrc: 'USAN20300027',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/46wsj9yMktwifcIhXhqj1b',
    },
    href: 'https://api.spotify.com/v1/tracks/46wsj9yMktwifcIhXhqj1b',
    id: '46wsj9yMktwifcIhXhqj1b',
    is_playable: true,
    linked_from: {
      external_urls: {
        spotify: 'https://open.spotify.com/track/5gIJUFDYsyNzRGBcS3lVcX',
      },
      href: 'https://api.spotify.com/v1/tracks/5gIJUFDYsyNzRGBcS3lVcX',
      id: '5gIJUFDYsyNzRGBcS3lVcX',
      type: 'track',
      uri: 'spotify:track:5gIJUFDYsyNzRGBcS3lVcX',
    },
    name: 'Remember When',
    popularity: 50,
    preview_url:
      'https://p.scdn.co/mp3-preview/dbe39acd3a8cb62e39e64f04ee2f9a53bbec00ab?cid=860f7e542d28458ba23dd153a3319256',
    track_number: 18,
    type: 'track',
    uri: 'spotify:track:46wsj9yMktwifcIhXhqj1b',
    is_local: false,
  },
  {
    album: {
      album_type: 'COMPILATION',
      total_tracks: 15,
      external_urls: {
        spotify: 'https://open.spotify.com/album/0UCCMRZib7d6eCdEWQiPJ3',
      },
      href: 'https://api.spotify.com/v1/albums/0UCCMRZib7d6eCdEWQiPJ3',
      id: '0UCCMRZib7d6eCdEWQiPJ3',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b273fb9cb0832b7e12bde6032b83',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e02fb9cb0832b7e12bde6032b83',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00004851fb9cb0832b7e12bde6032b83',
          height: 64,
          width: 64,
        },
      ],
      name: 'On the Other Hand - All the Number Ones',
      release_date: '2015-04-21',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:0UCCMRZib7d6eCdEWQiPJ3',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/1pTuR132U5b4Rizal2Pr7m',
          },
          href: 'https://api.spotify.com/v1/artists/1pTuR132U5b4Rizal2Pr7m',
          id: '1pTuR132U5b4Rizal2Pr7m',
          name: 'Randy Travis',
          type: 'artist',
          uri: 'spotify:artist:1pTuR132U5b4Rizal2Pr7m',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/1pTuR132U5b4Rizal2Pr7m',
        },
        href: 'https://api.spotify.com/v1/artists/1pTuR132U5b4Rizal2Pr7m',
        id: '1pTuR132U5b4Rizal2Pr7m',
        name: 'Randy Travis',
        type: 'artist',
        uri: 'spotify:artist:1pTuR132U5b4Rizal2Pr7m',
      },
    ],
    disc_number: 1,
    duration_ms: 201266,
    explicit: false,
    external_ids: {
      isrc: 'USWB11504483',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/1S4fpfX2u0hzFD9vb6FEB6',
    },
    href: 'https://api.spotify.com/v1/tracks/1S4fpfX2u0hzFD9vb6FEB6',
    id: '1S4fpfX2u0hzFD9vb6FEB6',
    is_playable: true,
    name: 'Three Wooden Crosses',
    popularity: 62,
    preview_url:
      'https://p.scdn.co/mp3-preview/e94facc3ec4ac7512eca9076442a8f224189fb21?cid=860f7e542d28458ba23dd153a3319256',
    track_number: 15,
    type: 'track',
    uri: 'spotify:track:1S4fpfX2u0hzFD9vb6FEB6',
    is_local: false,
  },
  {
    album: {
      album_type: 'SINGLE',
      total_tracks: 1,
      external_urls: {
        spotify: 'https://open.spotify.com/album/4UvHEhx0tQXpzIk4lGPn18',
      },
      href: 'https://api.spotify.com/v1/albums/4UvHEhx0tQXpzIk4lGPn18',
      id: '4UvHEhx0tQXpzIk4lGPn18',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b2730d6abf57a10a2ac961b96ce7',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e020d6abf57a10a2ac961b96ce7',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d000048510d6abf57a10a2ac961b96ce7',
          height: 64,
          width: 64,
        },
      ],
      name: "Don't Waste the Night",
      release_date: '2017-04-28',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:4UvHEhx0tQXpzIk4lGPn18',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/64fJiKnU2RfnndB8xP3gLi',
          },
          href: 'https://api.spotify.com/v1/artists/64fJiKnU2RfnndB8xP3gLi',
          id: '64fJiKnU2RfnndB8xP3gLi',
          name: 'Levi Hummon',
          type: 'artist',
          uri: 'spotify:artist:64fJiKnU2RfnndB8xP3gLi',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/64fJiKnU2RfnndB8xP3gLi',
        },
        href: 'https://api.spotify.com/v1/artists/64fJiKnU2RfnndB8xP3gLi',
        id: '64fJiKnU2RfnndB8xP3gLi',
        name: 'Levi Hummon',
        type: 'artist',
        uri: 'spotify:artist:64fJiKnU2RfnndB8xP3gLi',
      },
    ],
    disc_number: 1,
    duration_ms: 175773,
    explicit: false,
    external_ids: {
      isrc: 'QM88S1701000',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/39DvivKXIbyqUzTqaku3fT',
    },
    href: 'https://api.spotify.com/v1/tracks/39DvivKXIbyqUzTqaku3fT',
    id: '39DvivKXIbyqUzTqaku3fT',
    is_playable: true,
    name: "Don't Waste the Night",
    popularity: 28,
    preview_url:
      'https://p.scdn.co/mp3-preview/812abe3c1d4941c5701a98045be23b1f99447cfe?cid=860f7e542d28458ba23dd153a3319256',
    track_number: 1,
    type: 'track',
    uri: 'spotify:track:39DvivKXIbyqUzTqaku3fT',
    is_local: false,
  },
  {
    album: {
      album_type: 'SINGLE',
      total_tracks: 1,
      external_urls: {
        spotify: 'https://open.spotify.com/album/4tYabvVm8GlioIc5Tv7FzM',
      },
      href: 'https://api.spotify.com/v1/albums/4tYabvVm8GlioIc5Tv7FzM',
      id: '4tYabvVm8GlioIc5Tv7FzM',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b2731a7a956544a56923d479d85f',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e021a7a956544a56923d479d85f',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d000048511a7a956544a56923d479d85f',
          height: 64,
          width: 64,
        },
      ],
      name: 'When It Comes To Loving You',
      release_date: '2018-08-23',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:4tYabvVm8GlioIc5Tv7FzM',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/4BANbHDs1IluagTx5eRW2P',
          },
          href: 'https://api.spotify.com/v1/artists/4BANbHDs1IluagTx5eRW2P',
          id: '4BANbHDs1IluagTx5eRW2P',
          name: 'Jon Langston',
          type: 'artist',
          uri: 'spotify:artist:4BANbHDs1IluagTx5eRW2P',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/4BANbHDs1IluagTx5eRW2P',
        },
        href: 'https://api.spotify.com/v1/artists/4BANbHDs1IluagTx5eRW2P',
        id: '4BANbHDs1IluagTx5eRW2P',
        name: 'Jon Langston',
        type: 'artist',
        uri: 'spotify:artist:4BANbHDs1IluagTx5eRW2P',
      },
    ],
    disc_number: 1,
    duration_ms: 211600,
    explicit: false,
    external_ids: {
      isrc: 'QZ5AB1845218',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/27P7Xd23MGQigzpvm9tVmH',
    },
    href: 'https://api.spotify.com/v1/tracks/27P7Xd23MGQigzpvm9tVmH',
    id: '27P7Xd23MGQigzpvm9tVmH',
    is_playable: true,
    linked_from: {
      external_urls: {
        spotify: 'https://open.spotify.com/track/28dfxTgOAmwM1DhplcIB7G',
      },
      href: 'https://api.spotify.com/v1/tracks/28dfxTgOAmwM1DhplcIB7G',
      id: '28dfxTgOAmwM1DhplcIB7G',
      type: 'track',
      uri: 'spotify:track:28dfxTgOAmwM1DhplcIB7G',
    },
    name: 'When It Comes To Loving You',
    popularity: 50,
    preview_url: null,
    track_number: 3,
    type: 'track',
    uri: 'spotify:track:27P7Xd23MGQigzpvm9tVmH',
    is_local: false,
  },
  {
    album: {
      album_type: 'ALBUM',
      total_tracks: 14,
      external_urls: {
        spotify: 'https://open.spotify.com/album/4R6CBTblAXNOexIDEK4yNu',
      },
      href: 'https://api.spotify.com/v1/albums/4R6CBTblAXNOexIDEK4yNu',
      id: '4R6CBTblAXNOexIDEK4yNu',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b2737646f22eba3599fdeb6b7911',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e027646f22eba3599fdeb6b7911',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d000048517646f22eba3599fdeb6b7911',
          height: 64,
          width: 64,
        },
      ],
      name: 'When The Good Guys Win',
      release_date: '2017-10-27',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:4R6CBTblAXNOexIDEK4yNu',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/4sTFGCigAQIUiEy8wSSQNF',
          },
          href: 'https://api.spotify.com/v1/artists/4sTFGCigAQIUiEy8wSSQNF',
          id: '4sTFGCigAQIUiEy8wSSQNF',
          name: 'Granger Smith',
          type: 'artist',
          uri: 'spotify:artist:4sTFGCigAQIUiEy8wSSQNF',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/4sTFGCigAQIUiEy8wSSQNF',
        },
        href: 'https://api.spotify.com/v1/artists/4sTFGCigAQIUiEy8wSSQNF',
        id: '4sTFGCigAQIUiEy8wSSQNF',
        name: 'Granger Smith',
        type: 'artist',
        uri: 'spotify:artist:4sTFGCigAQIUiEy8wSSQNF',
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/2fTNvkLCMQkrFLxid6yHPG',
        },
        href: 'https://api.spotify.com/v1/artists/2fTNvkLCMQkrFLxid6yHPG',
        id: '2fTNvkLCMQkrFLxid6yHPG',
        name: 'Earl Dibbles Jr.',
        type: 'artist',
        uri: 'spotify:artist:2fTNvkLCMQkrFLxid6yHPG',
      },
    ],
    disc_number: 1,
    duration_ms: 214280,
    explicit: false,
    external_ids: {
      isrc: 'QMRSZ1702570',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/4JNdKmSZRsYDBwhIgZpa5M',
    },
    href: 'https://api.spotify.com/v1/tracks/4JNdKmSZRsYDBwhIgZpa5M',
    id: '4JNdKmSZRsYDBwhIgZpa5M',
    is_playable: true,
    name: "Don't Tread on Me (feat. Earl Dibbles Jr.)",
    popularity: 55,
    preview_url:
      'https://p.scdn.co/mp3-preview/6f93dc775b30cd8c61e92e4865711df019fe8fc4?cid=860f7e542d28458ba23dd153a3319256',
    track_number: 13,
    type: 'track',
    uri: 'spotify:track:4JNdKmSZRsYDBwhIgZpa5M',
    is_local: false,
  },
  {
    album: {
      album_type: 'ALBUM',
      total_tracks: 10,
      external_urls: {
        spotify: 'https://open.spotify.com/album/4agxyxFq9Onbm5jP8v3On4',
      },
      href: 'https://api.spotify.com/v1/albums/4agxyxFq9Onbm5jP8v3On4',
      id: '4agxyxFq9Onbm5jP8v3On4',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b273d78a00842f2c6c3dca31ce1f',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e02d78a00842f2c6c3dca31ce1f',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00004851d78a00842f2c6c3dca31ce1f',
          height: 64,
          width: 64,
        },
      ],
      name: 'Super Hits',
      release_date: '2003',
      release_date_precision: 'year',
      type: 'album',
      uri: 'spotify:album:4agxyxFq9Onbm5jP8v3On4',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/3Ay15wt0QChT4Kapsuw5Jt',
          },
          href: 'https://api.spotify.com/v1/artists/3Ay15wt0QChT4Kapsuw5Jt',
          id: '3Ay15wt0QChT4Kapsuw5Jt',
          name: 'Clint Black',
          type: 'artist',
          uri: 'spotify:artist:3Ay15wt0QChT4Kapsuw5Jt',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/3Ay15wt0QChT4Kapsuw5Jt',
        },
        href: 'https://api.spotify.com/v1/artists/3Ay15wt0QChT4Kapsuw5Jt',
        id: '3Ay15wt0QChT4Kapsuw5Jt',
        name: 'Clint Black',
        type: 'artist',
        uri: 'spotify:artist:3Ay15wt0QChT4Kapsuw5Jt',
      },
    ],
    disc_number: 1,
    duration_ms: 261533,
    explicit: false,
    external_ids: {
      isrc: 'USRN10200901',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/25IXknfqkMuACBD5jeRv60',
    },
    href: 'https://api.spotify.com/v1/tracks/25IXknfqkMuACBD5jeRv60',
    id: '25IXknfqkMuACBD5jeRv60',
    is_playable: true,
    name: 'Like The Rain',
    popularity: 56,
    preview_url:
      'https://p.scdn.co/mp3-preview/8324b67d646288d03f7f1a544740b545374e7f51?cid=860f7e542d28458ba23dd153a3319256',
    track_number: 4,
    type: 'track',
    uri: 'spotify:track:25IXknfqkMuACBD5jeRv60',
    is_local: false,
  },
  {
    album: {
      album_type: 'SINGLE',
      total_tracks: 1,
      external_urls: {
        spotify: 'https://open.spotify.com/album/5lNJok4JwdOMq9ReGAeoTp',
      },
      href: 'https://api.spotify.com/v1/albums/5lNJok4JwdOMq9ReGAeoTp',
      id: '5lNJok4JwdOMq9ReGAeoTp',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b27314cefe977f895c21685dc7b6',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e0214cefe977f895c21685dc7b6',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d0000485114cefe977f895c21685dc7b6',
          height: 64,
          width: 64,
        },
      ],
      name: 'Hoping',
      release_date: '2017-06-02',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:5lNJok4JwdOMq9ReGAeoTp',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/6NBjdxIPyMnOSmkkwd5UZT',
          },
          href: 'https://api.spotify.com/v1/artists/6NBjdxIPyMnOSmkkwd5UZT',
          id: '6NBjdxIPyMnOSmkkwd5UZT',
          name: 'Temecula Road',
          type: 'artist',
          uri: 'spotify:artist:6NBjdxIPyMnOSmkkwd5UZT',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/6NBjdxIPyMnOSmkkwd5UZT',
        },
        href: 'https://api.spotify.com/v1/artists/6NBjdxIPyMnOSmkkwd5UZT',
        id: '6NBjdxIPyMnOSmkkwd5UZT',
        name: 'Temecula Road',
        type: 'artist',
        uri: 'spotify:artist:6NBjdxIPyMnOSmkkwd5UZT',
      },
    ],
    disc_number: 1,
    duration_ms: 205000,
    explicit: false,
    external_ids: {
      isrc: 'USR1B1721659',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/12Vc0DlsB3IlAs6GwbcB3Q',
    },
    href: 'https://api.spotify.com/v1/tracks/12Vc0DlsB3IlAs6GwbcB3Q',
    id: '12Vc0DlsB3IlAs6GwbcB3Q',
    is_playable: true,
    name: 'Hoping',
    popularity: 15,
    preview_url: null,
    track_number: 1,
    type: 'track',
    uri: 'spotify:track:12Vc0DlsB3IlAs6GwbcB3Q',
    is_local: false,
  },
  {
    album: {
      album_type: 'COMPILATION',
      total_tracks: 19,
      external_urls: {
        spotify: 'https://open.spotify.com/album/7i9SBViXieoiyjxoYcOXWJ',
      },
      href: 'https://api.spotify.com/v1/albums/7i9SBViXieoiyjxoYcOXWJ',
      id: '7i9SBViXieoiyjxoYcOXWJ',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b273a7cc5f4fb2744c794658b5a0',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e02a7cc5f4fb2744c794658b5a0',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00004851a7cc5f4fb2744c794658b5a0',
          height: 64,
          width: 64,
        },
      ],
      name: 'The Best Of George Jones',
      release_date: '1998-01-01',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:7i9SBViXieoiyjxoYcOXWJ',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/2OpqcUtj10HHvGG6h9VYC5',
          },
          href: 'https://api.spotify.com/v1/artists/2OpqcUtj10HHvGG6h9VYC5',
          id: '2OpqcUtj10HHvGG6h9VYC5',
          name: 'George Jones',
          type: 'artist',
          uri: 'spotify:artist:2OpqcUtj10HHvGG6h9VYC5',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/2OpqcUtj10HHvGG6h9VYC5',
        },
        href: 'https://api.spotify.com/v1/artists/2OpqcUtj10HHvGG6h9VYC5',
        id: '2OpqcUtj10HHvGG6h9VYC5',
        name: 'George Jones',
        type: 'artist',
        uri: 'spotify:artist:2OpqcUtj10HHvGG6h9VYC5',
      },
    ],
    disc_number: 1,
    duration_ms: 165453,
    explicit: false,
    external_ids: {
      isrc: 'USPR35802412',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/7o68KX6XyCS9lydBTH6TCP',
    },
    href: 'https://api.spotify.com/v1/tracks/7o68KX6XyCS9lydBTH6TCP',
    id: '7o68KX6XyCS9lydBTH6TCP',
    is_playable: true,
    linked_from: {
      external_urls: {
        spotify: 'https://open.spotify.com/track/6HkLfGqh1L4dH9HbrYrAEu',
      },
      href: 'https://api.spotify.com/v1/tracks/6HkLfGqh1L4dH9HbrYrAEu',
      id: '6HkLfGqh1L4dH9HbrYrAEu',
      type: 'track',
      uri: 'spotify:track:6HkLfGqh1L4dH9HbrYrAEu',
    },
    name: 'White Lightning - Single Version',
    popularity: 52,
    preview_url: null,
    track_number: 4,
    type: 'track',
    uri: 'spotify:track:7o68KX6XyCS9lydBTH6TCP',
    is_local: false,
  },
  {
    album: {
      album_type: 'ALBUM',
      total_tracks: 12,
      external_urls: {
        spotify: 'https://open.spotify.com/album/1zgQkZFMRqx1Lz9GVXghLt',
      },
      href: 'https://api.spotify.com/v1/albums/1zgQkZFMRqx1Lz9GVXghLt',
      id: '1zgQkZFMRqx1Lz9GVXghLt',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b27389847614971c417b722c4d97',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e0289847614971c417b722c4d97',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d0000485189847614971c417b722c4d97',
          height: 64,
          width: 64,
        },
      ],
      name: 'Home',
      release_date: '2002-08-27',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:1zgQkZFMRqx1Lz9GVXghLt',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/25IG9fa7cbdmCIy3OnuH57',
          },
          href: 'https://api.spotify.com/v1/artists/25IG9fa7cbdmCIy3OnuH57',
          id: '25IG9fa7cbdmCIy3OnuH57',
          name: 'The Chicks',
          type: 'artist',
          uri: 'spotify:artist:25IG9fa7cbdmCIy3OnuH57',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/25IG9fa7cbdmCIy3OnuH57',
        },
        href: 'https://api.spotify.com/v1/artists/25IG9fa7cbdmCIy3OnuH57',
        id: '25IG9fa7cbdmCIy3OnuH57',
        name: 'The Chicks',
        type: 'artist',
        uri: 'spotify:artist:25IG9fa7cbdmCIy3OnuH57',
      },
    ],
    disc_number: 1,
    duration_ms: 343496,
    explicit: false,
    external_ids: {
      isrc: 'USSM10209595',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/0AkZjWYCMJ8wWiNex7LmkY',
    },
    href: 'https://api.spotify.com/v1/tracks/0AkZjWYCMJ8wWiNex7LmkY',
    id: '0AkZjWYCMJ8wWiNex7LmkY',
    is_playable: true,
    name: "Travelin' Soldier",
    popularity: 68,
    preview_url:
      'https://p.scdn.co/mp3-preview/26b55f55e7bc0d13fd8a4670e1c68661f29f86ee?cid=860f7e542d28458ba23dd153a3319256',
    track_number: 3,
    type: 'track',
    uri: 'spotify:track:0AkZjWYCMJ8wWiNex7LmkY',
    is_local: false,
  },
  {
    album: {
      album_type: 'ALBUM',
      total_tracks: 10,
      external_urls: {
        spotify: 'https://open.spotify.com/album/3F88UQZzP3fmw2p3m2j9l5',
      },
      href: 'https://api.spotify.com/v1/albums/3F88UQZzP3fmw2p3m2j9l5',
      id: '3F88UQZzP3fmw2p3m2j9l5',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b273ba39c0f3ea158d2210eb7dce',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e02ba39c0f3ea158d2210eb7dce',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00004851ba39c0f3ea158d2210eb7dce',
          height: 64,
          width: 64,
        },
      ],
      name: "I'm Countryfied",
      release_date: '1980-11-10',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:3F88UQZzP3fmw2p3m2j9l5',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/1fMdO9vLUd6wW4jbMeNiup',
          },
          href: 'https://api.spotify.com/v1/artists/1fMdO9vLUd6wW4jbMeNiup',
          id: '1fMdO9vLUd6wW4jbMeNiup',
          name: 'Mel McDaniel',
          type: 'artist',
          uri: 'spotify:artist:1fMdO9vLUd6wW4jbMeNiup',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/1fMdO9vLUd6wW4jbMeNiup',
        },
        href: 'https://api.spotify.com/v1/artists/1fMdO9vLUd6wW4jbMeNiup',
        id: '1fMdO9vLUd6wW4jbMeNiup',
        name: 'Mel McDaniel',
        type: 'artist',
        uri: 'spotify:artist:1fMdO9vLUd6wW4jbMeNiup',
      },
    ],
    disc_number: 1,
    duration_ms: 144186,
    explicit: false,
    external_ids: {
      isrc: 'USCN18000051',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/50PU05RTGva8laKDwxED9Y',
    },
    href: 'https://api.spotify.com/v1/tracks/50PU05RTGva8laKDwxED9Y',
    id: '50PU05RTGva8laKDwxED9Y',
    is_playable: true,
    name: 'Louisiana Saturday Night',
    popularity: 71,
    preview_url: null,
    track_number: 1,
    type: 'track',
    uri: 'spotify:track:50PU05RTGva8laKDwxED9Y',
    is_local: false,
  },
  {
    album: {
      album_type: 'ALBUM',
      total_tracks: 8,
      external_urls: {
        spotify: 'https://open.spotify.com/album/4cJEaCh5E1LTKbG4rY3GYQ',
      },
      href: 'https://api.spotify.com/v1/albums/4cJEaCh5E1LTKbG4rY3GYQ',
      id: '4cJEaCh5E1LTKbG4rY3GYQ',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b273dc2cc03d443fe5c7e16893d3',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e02dc2cc03d443fe5c7e16893d3',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00004851dc2cc03d443fe5c7e16893d3',
          height: 64,
          width: 64,
        },
      ],
      name: 'Undeniably Country',
      release_date: '2016-11-18',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:4cJEaCh5E1LTKbG4rY3GYQ',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/21NiIObyfGUR3UPql6UrkP',
          },
          href: 'https://api.spotify.com/v1/artists/21NiIObyfGUR3UPql6UrkP',
          id: '21NiIObyfGUR3UPql6UrkP',
          name: 'Curtis Grimes',
          type: 'artist',
          uri: 'spotify:artist:21NiIObyfGUR3UPql6UrkP',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/21NiIObyfGUR3UPql6UrkP',
        },
        href: 'https://api.spotify.com/v1/artists/21NiIObyfGUR3UPql6UrkP',
        id: '21NiIObyfGUR3UPql6UrkP',
        name: 'Curtis Grimes',
        type: 'artist',
        uri: 'spotify:artist:21NiIObyfGUR3UPql6UrkP',
      },
    ],
    disc_number: 1,
    duration_ms: 191840,
    explicit: false,
    external_ids: {
      isrc: 'TCACS1644842',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/2sbMXKt8HI1YhMDdWOsNWi',
    },
    href: 'https://api.spotify.com/v1/tracks/2sbMXKt8HI1YhMDdWOsNWi',
    id: '2sbMXKt8HI1YhMDdWOsNWi',
    is_playable: true,
    linked_from: {
      external_urls: {
        spotify: 'https://open.spotify.com/track/6EUEnvlcNhfkWhZFy0GZI5',
      },
      href: 'https://api.spotify.com/v1/tracks/6EUEnvlcNhfkWhZFy0GZI5',
      id: '6EUEnvlcNhfkWhZFy0GZI5',
      type: 'track',
      uri: 'spotify:track:6EUEnvlcNhfkWhZFy0GZI5',
    },
    name: "From Where I'm Standing",
    popularity: 46,
    preview_url:
      'https://p.scdn.co/mp3-preview/47051ba26d9194f58b985b65e1c284b2b41e21d5?cid=860f7e542d28458ba23dd153a3319256',
    track_number: 3,
    type: 'track',
    uri: 'spotify:track:2sbMXKt8HI1YhMDdWOsNWi',
    is_local: false,
  },
  {
    album: {
      album_type: 'SINGLE',
      total_tracks: 4,
      external_urls: {
        spotify: 'https://open.spotify.com/album/6wVnoDiRPI8RDgQT2RH3PO',
      },
      href: 'https://api.spotify.com/v1/albums/6wVnoDiRPI8RDgQT2RH3PO',
      id: '6wVnoDiRPI8RDgQT2RH3PO',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b273b2d68acb99f6d9269ad53f11',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e02b2d68acb99f6d9269ad53f11',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00004851b2d68acb99f6d9269ad53f11',
          height: 64,
          width: 64,
        },
      ],
      name: 'Ryan Hurd - EP',
      release_date: '2017-04-07',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:6wVnoDiRPI8RDgQT2RH3PO',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/7lDVEkjIURPMyUYwoQRrpw',
          },
          href: 'https://api.spotify.com/v1/artists/7lDVEkjIURPMyUYwoQRrpw',
          id: '7lDVEkjIURPMyUYwoQRrpw',
          name: 'Ryan Hurd',
          type: 'artist',
          uri: 'spotify:artist:7lDVEkjIURPMyUYwoQRrpw',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/7lDVEkjIURPMyUYwoQRrpw',
        },
        href: 'https://api.spotify.com/v1/artists/7lDVEkjIURPMyUYwoQRrpw',
        id: '7lDVEkjIURPMyUYwoQRrpw',
        name: 'Ryan Hurd',
        type: 'artist',
        uri: 'spotify:artist:7lDVEkjIURPMyUYwoQRrpw',
      },
    ],
    disc_number: 1,
    duration_ms: 214177,
    explicit: false,
    external_ids: {
      isrc: 'USRN11600952',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/1vtlFENFwePxExgcz8STd8',
    },
    href: 'https://api.spotify.com/v1/tracks/1vtlFENFwePxExgcz8STd8',
    id: '1vtlFENFwePxExgcz8STd8',
    is_playable: true,
    name: 'Hold You Back',
    popularity: 39,
    preview_url:
      'https://p.scdn.co/mp3-preview/dce150344b458e8f11f213d23e96385ff2d2484e?cid=860f7e542d28458ba23dd153a3319256',
    track_number: 4,
    type: 'track',
    uri: 'spotify:track:1vtlFENFwePxExgcz8STd8',
    is_local: false,
  },
  {
    album: {
      album_type: 'ALBUM',
      total_tracks: 12,
      external_urls: {
        spotify: 'https://open.spotify.com/album/2SxBuClrOCg8WZPXEDobmm',
      },
      href: 'https://api.spotify.com/v1/albums/2SxBuClrOCg8WZPXEDobmm',
      id: '2SxBuClrOCg8WZPXEDobmm',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b2735a6952e2a6f47654f1f249bf',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e025a6952e2a6f47654f1f249bf',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d000048515a6952e2a6f47654f1f249bf',
          height: 64,
          width: 64,
        },
      ],
      name: 'All of It',
      release_date: '2018-08-17',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:2SxBuClrOCg8WZPXEDobmm',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/1mfDfLsMxYcOOZkzBxvSVW',
          },
          href: 'https://api.spotify.com/v1/artists/1mfDfLsMxYcOOZkzBxvSVW',
          id: '1mfDfLsMxYcOOZkzBxvSVW',
          name: 'Cole Swindell',
          type: 'artist',
          uri: 'spotify:artist:1mfDfLsMxYcOOZkzBxvSVW',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/1mfDfLsMxYcOOZkzBxvSVW',
        },
        href: 'https://api.spotify.com/v1/artists/1mfDfLsMxYcOOZkzBxvSVW',
        id: '1mfDfLsMxYcOOZkzBxvSVW',
        name: 'Cole Swindell',
        type: 'artist',
        uri: 'spotify:artist:1mfDfLsMxYcOOZkzBxvSVW',
      },
    ],
    disc_number: 1,
    duration_ms: 225266,
    explicit: false,
    external_ids: {
      isrc: 'USWB11800719',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/3OBHpK5sbRBj3xQLCFcBLt',
    },
    href: 'https://api.spotify.com/v1/tracks/3OBHpK5sbRBj3xQLCFcBLt',
    id: '3OBHpK5sbRBj3xQLCFcBLt',
    is_playable: true,
    name: "Somebody's Been Drinkin'",
    popularity: 42,
    preview_url:
      'https://p.scdn.co/mp3-preview/35fb1b650592873e8f307a9032b919d67e5f5e58?cid=860f7e542d28458ba23dd153a3319256',
    track_number: 3,
    type: 'track',
    uri: 'spotify:track:3OBHpK5sbRBj3xQLCFcBLt',
    is_local: false,
  },
  {
    album: {
      album_type: 'ALBUM',
      total_tracks: 12,
      external_urls: {
        spotify: 'https://open.spotify.com/album/5tvHSuAIkmG9UD8jAmnXup',
      },
      href: 'https://api.spotify.com/v1/albums/5tvHSuAIkmG9UD8jAmnXup',
      id: '5tvHSuAIkmG9UD8jAmnXup',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b27324e1535df4d2e28dd96d7b8e',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e0224e1535df4d2e28dd96d7b8e',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d0000485124e1535df4d2e28dd96d7b8e',
          height: 64,
          width: 64,
        },
      ],
      name: 'Randy Rogers Band',
      release_date: '2008-01-01',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:5tvHSuAIkmG9UD8jAmnXup',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/04DUpHOyQqwbHFyvIhcGi3',
          },
          href: 'https://api.spotify.com/v1/artists/04DUpHOyQqwbHFyvIhcGi3',
          id: '04DUpHOyQqwbHFyvIhcGi3',
          name: 'Randy Rogers Band',
          type: 'artist',
          uri: 'spotify:artist:04DUpHOyQqwbHFyvIhcGi3',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/04DUpHOyQqwbHFyvIhcGi3',
        },
        href: 'https://api.spotify.com/v1/artists/04DUpHOyQqwbHFyvIhcGi3',
        id: '04DUpHOyQqwbHFyvIhcGi3',
        name: 'Randy Rogers Band',
        type: 'artist',
        uri: 'spotify:artist:04DUpHOyQqwbHFyvIhcGi3',
      },
    ],
    disc_number: 1,
    duration_ms: 221626,
    explicit: false,
    external_ids: {
      isrc: 'USUM70813715',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/1EHNNWLiWe1PJADKEnMvIr',
    },
    href: 'https://api.spotify.com/v1/tracks/1EHNNWLiWe1PJADKEnMvIr',
    id: '1EHNNWLiWe1PJADKEnMvIr',
    is_playable: true,
    name: 'Buy Myself A Chance',
    popularity: 56,
    preview_url: null,
    track_number: 9,
    type: 'track',
    uri: 'spotify:track:1EHNNWLiWe1PJADKEnMvIr',
    is_local: false,
  },
  {
    album: {
      album_type: 'ALBUM',
      total_tracks: 11,
      external_urls: {
        spotify: 'https://open.spotify.com/album/7zD1Xp405071FTXmxySeD9',
      },
      href: 'https://api.spotify.com/v1/albums/7zD1Xp405071FTXmxySeD9',
      id: '7zD1Xp405071FTXmxySeD9',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b273f3e75bc21b56bbea85f64070',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e02f3e75bc21b56bbea85f64070',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00004851f3e75bc21b56bbea85f64070',
          height: 64,
          width: 64,
        },
      ],
      name: 'thirty one',
      release_date: '2015-10-09',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:7zD1Xp405071FTXmxySeD9',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/2PaRhxWFaqCUZybJDDoNrf',
          },
          href: 'https://api.spotify.com/v1/artists/2PaRhxWFaqCUZybJDDoNrf',
          id: '2PaRhxWFaqCUZybJDDoNrf',
          name: 'Jana Kramer',
          type: 'artist',
          uri: 'spotify:artist:2PaRhxWFaqCUZybJDDoNrf',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/2PaRhxWFaqCUZybJDDoNrf',
        },
        href: 'https://api.spotify.com/v1/artists/2PaRhxWFaqCUZybJDDoNrf',
        id: '2PaRhxWFaqCUZybJDDoNrf',
        name: 'Jana Kramer',
        type: 'artist',
        uri: 'spotify:artist:2PaRhxWFaqCUZybJDDoNrf',
      },
    ],
    disc_number: 1,
    duration_ms: 201013,
    explicit: false,
    external_ids: {
      isrc: 'USWB11500132',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/6tbNaE7kvGNqS7FvJ0dzLB',
    },
    href: 'https://api.spotify.com/v1/tracks/6tbNaE7kvGNqS7FvJ0dzLB',
    id: '6tbNaE7kvGNqS7FvJ0dzLB',
    is_playable: true,
    name: 'I Got the Boy',
    popularity: 59,
    preview_url:
      'https://p.scdn.co/mp3-preview/c7aedea244a995af163dd39bd6c553aa0c63e7da?cid=860f7e542d28458ba23dd153a3319256',
    track_number: 3,
    type: 'track',
    uri: 'spotify:track:6tbNaE7kvGNqS7FvJ0dzLB',
    is_local: false,
  },
  {
    album: {
      album_type: 'COMPILATION',
      total_tracks: 54,
      external_urls: {
        spotify: 'https://open.spotify.com/album/2deyKpm7P5GowjcFJ1OWEC',
      },
      href: 'https://api.spotify.com/v1/albums/2deyKpm7P5GowjcFJ1OWEC',
      id: '2deyKpm7P5GowjcFJ1OWEC',
      images: [
        {
          url: 'https://i.scdn.co/image/ab67616d0000b2734ea992d3d7a0dd145f8ee213',
          height: 640,
          width: 640,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d00001e024ea992d3d7a0dd145f8ee213',
          height: 300,
          width: 300,
        },
        {
          url: 'https://i.scdn.co/image/ab67616d000048514ea992d3d7a0dd145f8ee213',
          height: 64,
          width: 64,
        },
      ],
      name: 'Original Album Classics',
      release_date: '1989',
      release_date_precision: 'year',
      type: 'album',
      uri: 'spotify:album:2deyKpm7P5GowjcFJ1OWEC',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/4mxWe1mtYIYfP040G38yvS',
          },
          href: 'https://api.spotify.com/v1/artists/4mxWe1mtYIYfP040G38yvS',
          id: '4mxWe1mtYIYfP040G38yvS',
          name: 'Alan Jackson',
          type: 'artist',
          uri: 'spotify:artist:4mxWe1mtYIYfP040G38yvS',
        },
      ],
      is_playable: true,
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/4mxWe1mtYIYfP040G38yvS',
        },
        href: 'https://api.spotify.com/v1/artists/4mxWe1mtYIYfP040G38yvS',
        id: '4mxWe1mtYIYfP040G38yvS',
        name: 'Alan Jackson',
        type: 'artist',
        uri: 'spotify:artist:4mxWe1mtYIYfP040G38yvS',
      },
    ],
    disc_number: 1,
    duration_ms: 216893,
    explicit: false,
    external_ids: {
      isrc: 'USAN20300078',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/2lGx9cF0Z3xtkHE5Q36Yr3',
    },
    href: 'https://api.spotify.com/v1/tracks/2lGx9cF0Z3xtkHE5Q36Yr3',
    id: '2lGx9cF0Z3xtkHE5Q36Yr3',
    is_playable: true,
    linked_from: {
      external_urls: {
        spotify: 'https://open.spotify.com/track/5f7xuOs1CLKczft1RO5bmK',
      },
      href: 'https://api.spotify.com/v1/tracks/5f7xuOs1CLKczft1RO5bmK',
      id: '5f7xuOs1CLKczft1RO5bmK',
      type: 'track',
      uri: 'spotify:track:5f7xuOs1CLKczft1RO5bmK',
    },
    name: 'Here In the Real World',
    popularity: 41,
    preview_url:
      'https://p.scdn.co/mp3-preview/60b2862287e387ee8a44de720f28cdaeeb1f8b1a?cid=860f7e542d28458ba23dd153a3319256',
    track_number: 2,
    type: 'track',
    uri: 'spotify:track:2lGx9cF0Z3xtkHE5Q36Yr3',
    is_local: false,
  },
];
